services:
  mongodb:
    image: mongo:latest
    container_name: echocrm_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db 
    environment:
      MONGO_INITDB_DATABASE: echo_crm
    networks:
      - echocrm_network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: echocrm_rabbitmq
    ports:
      - "5672:5672"  
      - "15672:15672" 
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/ 
    environment:
      RABBITMQ_DEFAULT_USER: guest 
      RABBITMQ_DEFAULT_PASS: guest 
    networks:
      - echocrm_network
volumes:
  mongodb_data:
  rabbitmq_data:

networks:
  echocrm_network:
    driver: bridge